apiVersion: v1
kind: Service
metadata:
    name: "testakscluster-8f47"
    labels:
        app: "testakscluster-8f47"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "testakscluster-8f47"