on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n test132 -g test132a061-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n test132 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n test132 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n test132 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: test132.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/test1" -f  "test" -t test132.azurecr.io/testakscluster:${{ github.sha }}
        docker push test132.azurecr.io/testakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_testakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testaksclustera101 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testaksclustera101`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testaksclustera101
        container-registry-url: test132.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: testaksclustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testaksclustera101
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          test132.azurecr.io/testakscluster:${{ github.sha }}
        imagepullsecrets: |
          testaksclustdockerauth